#!/bin/bash

# Ask the user for a directory name to be created.
echo "Enter the directory name to be created:"
read dirname

# Create a new directory with that name and CD into it.
mkdir $dirname
cd ./$dirname

# Report the working directory.
echo "$dirname has been created"
echo "Moved into $( pwd )"

# Create a few files.
touch index.html
echo "# $dirname" > README.md
echo ".DS_Store" > .gitignore

# Initialize git.
git init
git add -A
git commit -m "Initial commit"

# Report the filenames that have been created.
ls -hartl

# Tell the user that this script is done.
echo "Done!"
